### ISSUE TITLE
ENH Convert weights of the 4 models into one large binary file

### ISSUE THREAD

**Issue by PABannier** [PABannier/bark.cpp#10]
Currently, the convert script generates 4 binary files corresponding to the weights and metadata of the 4 major components of bark. For simplicity purposes, we should make one big large file.

**Comment by PABannier** [comment]
Closing as this does not feel right now. Having 4 separate files seem easier to handle.

**Comment by Green-Sky** [comment]
i would suggest going for 1 gguf file in the future.

**Comment by PABannier** [comment]
absolutely! referencing it here: https://github.com/ggerganov/ggml/pull/302 

@Green-Sky still no mail?
