### ISSUE TITLE
MacBook

### ISSUE THREAD

**Issue by ehartford** [PABannier/bark.cpp#14]
Why do you want to make it only work on a MacBook?

If it works on a MacBook couldn't it work on other computers too?

Ggml works on any computer, couldn't this do the same?

**Comment by akarshanbiswas** [comment]
Really [where](https://github.com/PABannier/bark.cpp/blob/0a12b28c3bdfc24ec18bfa3eeb2af12c82f5994f/Makefile#L42)?

**Comment by PABannier** [comment]
Hi @ehartford ! `bark.cpp` should normally work on all platforms, not specifically on MacOS. #13 this PR adds a whole bunch of recipes for a wide set of instruction sets supported by MacOS and other platforms.

**Comment by Green-Sky** [comment]
I think he meant the README.md

> The main goal of bark.cpp is to synthesize audio from a textual input with the [Bark](https://github.com/suno-ai/bark) model using 4-bit quantization on a MacBook.

**Comment by PABannier** [comment]
You're right, this is misleading. I'll change it when I update the doc.

**Comment by ehartford** [comment]
Thank you!
