### ISSUE TITLE
missing requirements.txt

### ISSUE THREAD

**Issue by Green-Sky** [PABannier/bark.cpp#140]
The readme tells you to:
```
python3 -m pip install -r bark/requirements.txt
```
but there is no such file. It looks like it got accidentally removed.
https://github.com/PABannier/bark.cpp/blob/3c4411d33e7093fb6a5586463d40e2c196aa146a/bark/requirements.txt

**Comment by PABannier** [comment]
Good catch @Green-Sky ! Just reverted the change in #141 :) Thanks
