### ISSUE TITLE
preconverted model files

### ISSUE THREAD

**Issue by Green-Sky** [PABannier/bark.cpp#144]
Since the project got some fixes and the model files changed I uploaded some new converted model files.
https://huggingface.co/Green-Sky/bark-ggml

**Comment by PABannier** [comment]
This is amazing, thanks for the contribution @Green-Sky !

**Comment by Green-Sky** [comment]
I updated the model files.
Currently only f16 works, likely because encodec only works with f16 and its now merged in a single file and quantization seems to effect the whole file.

Also uploaded bark-small :)
