### ISSUE TITLE
encodec_weights.bin seems not produced by convert.py script

### ISSUE THREAD

**Issue by qnixsynapse** [PABannier/bark.cpp#146]
Also, the readme is missing important details. The main binary expects a ggml binary, not a folder.

Edit: Okay I have to convert encodec using the submodule's convert.py script.

**Comment by PABannier** [comment]
Hello @qnixsynapse !
The instructions have been updated. Could you tell me if this works now?

**Comment by qnixsynapse** [comment]
@PABannier  Hi. Sorry I am a bit busy these days. 

This needs to be fixed in readme:
```
# run the inference
./build/examples/main/main -m ./ggml_weights/ -em ./ggml_weights/encodec_weights.bin -p "this is an audio"

```

main -m expects a ggml file not a folder in my testing.

**Comment by PABannier** [comment]
@qnixsynapse Thanks for pointing this out. The instructions have been updated. With #151 , we now support `bark-small`, the instructions are clearer.
