### ISSUE TITLE
`bark_generate_audio` accepts an output path but does not actually write to it

### ISSUE THREAD

**Issue by sindresorhus** [PABannier/bark.cpp#156]
https://github.com/PABannier/bark.cpp/blob/d8bd0fd05d4d688547e31979d77e88381ed3e1f2/bark.cpp#L2065C6-L2066

The parameter should either be removed or it should write to the given output path. I would prefer the latter, as most use-cases for this is to simply write to a WAV file, and it would be nice if this library took care of it.

**Comment by PABannier** [comment]
Hi @sindresorhus ! Thanks for catching this!
This has been removed in #155 .
Closing as this is solved.
