### ISSUE TITLE
Add progress callback

### ISSUE THREAD

**Issue by sindresorhus** [PABannier/bark.cpp#157]
Something similar to what's done in Whisper.cpp: https://github.com/ggerganov/whisper.cpp/blob/b0c3cbf2e851cf232e432b590dcc514a689ec028/whisper.h#L553-L554

**Comment by PABannier** [comment]
Hello @sindresorhus ! We already have `BarkProgressBar` for progress updates: https://github.com/PABannier/bark.cpp/blob/main/bark.cpp#L33

Why would you like to have a `progress_callback`? Do you have a particular use case in mind?

**Comment by sindresorhus** [comment]
I'm considering integrating Bark.cpp in a macOS app, and I would need to show a progress bar while it's generating.

**Comment by PABannier** [comment]
I added a progress callback in #173 :) @sindresorhus
