### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by sindresorhus** [PABannier/bark.cpp#159]
This would make it much easier to use the package in Swift projects like iOS or macOS apps.

Could do something similar to what's done in Whisper.cpp: https://github.com/ggerganov/whisper.cpp/blob/master/Package.swift

**Comment by PABannier** [comment]
Hi @sindresorhus ! I just merged #169 which adds an example on SwiftUI. I'll have a look at your issues #157 and #158 later today ;)

**Comment by sindresorhus** [comment]
@PABannier Thank you 👍

However, the Package.swift is not working. The example project is not actually testing Package.swift because it uses a lot of symlinks instead. The correct way to use a local Swift package is to simply drag the folder of the package (the top-level "bark.cpp" folder) into the sidebar of Xcode (under "bark.swiftui). Then it should show up as a package there. Then delete the symlinks. I would have done a PR, but it fails to build after that, and I'm not familiar enough with a C++ project to fix it...
