### ISSUE TITLE
model quantize bad encodec

### ISSUE THREAD

**Issue by Gabri94x** [PABannier/bark.cpp#167]
hi there, i'm not pretty sure if it a bug or i missed something in my quantization process but this is the result i have running the q4_0 model 
![image](https://github.com/PABannier/bark.cpp/assets/79253682/5d47a0a4-5414-4d05-b507-dee4067b396a)
this the code line i made for quantization
![image](https://github.com/PABannier/bark.cpp/assets/79253682/45630d09-b5a0-4a96-b536-55b4264332b5)
this is the running line 
![image](https://github.com/PABannier/bark.cpp/assets/79253682/896e6098-ff0d-44f2-b3de-21053f8d65f2)
thank you for the project, it is really great and saves a lot of work!

**Comment by PABannier** [comment]
Hello @Gabri94x ! Actually encodec.cpp is not quantized due to the minor gains it brings to this model. I'll have a look at the quantization for bark to make sure it works.

**Comment by bachittle** [comment]
Yea I'm getting the same issue as well. It seems to occur with all quantization types, like q4_1, q8_0, etc.

**Comment by PABannier** [comment]
Hello all! This should be fixed in #176 . Could you try again and let me know?

**Comment by bachittle** [comment]
seems to be working now! now just new issues to address, like that the quantized models are slower than regular model. can probably close this issue now tho.

**Comment by PABannier** [comment]
Ok thanks for confirming :)
