### ISSUE TITLE
License of this repository

### ISSUE THREAD

**Issue by vietanhdev** [PABannier/bark.cpp#8]
Hi!
You are building a great project. I plan to use it in my next open source. However, I need to know the license of the project before starting with it.
Could you add a LICENSE file so that we can know what we can do with this project? 
Thank you very much!

**Comment by PABannier** [comment]
Hi @vietanhdev !
Thank you for your feedback. The project is currently under development. I plan to be done by the end of this week. 
I'll surely be adding a LICENSE file by this time!
