### ISSUE TITLE
Quantize doesn't seem to work for codec model

### ISSUE THREAD

**Issue by jzeiber** [PABannier/bark.cpp#88]
The text, coarse, and fine models are converted successfully, but the codec model always results in a 0 byte output.  After a quick look, it seems the header in the codec model may be slightly different than the other models and it can't read the correct ftype from the file because the offsets are wrong.

Additionally, running the models as f32 or f16 produces very similar output for the same prompt/seed.  Running the text, coarse, and fine models quantized at q8_0 produces an entirely different output for the same prompt/seed.

**Comment by PABannier** [comment]
Hi @jzeiber ! You're right it's not working for the codec model. I made a mistake in the README file, by including a command to quantize the codec model. 
Some functions in GGML do not support yet quantized tensors. Fortunately, the codec part is fast compared to the forward pass of the GPT encoders, which need to be run several hundreds times to generate tokens.

I'm changing the README file.

**Comment by SammyBravo** [comment]
Can we include some inference times on the README file for the quantized versions?

**Comment by BarfingLemurs** [comment]
@SammyBravo on my results, there is a slowdown compare to running in fp16. Additionally, it seems during inference the same amount of memory is required.

**Comment by PABannier** [comment]
@BarfingLemurs This is not what I am observing.. I'm currently running a set of benchmarks. I'll update the README with detailed instructions for quantization (cc @SammyBravo ).
What are the specs of your machine? Which prompt did you use? How much memory is required for the prompt you used?

**Comment by BarfingLemurs** [comment]
@PABannier Sorry, I misreported.
